execute: main.cpp WindowFeature.h WindowFeature.cpp HOG.h HOG.cpp LBP.cpp LBP.h ImageWindowIterator.h ImageWindowIterator.cpp
	clang++ WindowFeature.cpp HOG.cpp LBP.cpp ImageWindowIterator.cpp main.cpp -o execute 



