package:
  name: menpo
  version: {{ environ['CONDACI_VERSION'] }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10,<2.0
    - cython >=0.23

  run:
    - python
    - pathlib 1.0  # [py2k]

    # Scientific Python Stack
    - numpy >=1.10,<2.0
    - scipy >=0.16,<1.0
    - pillow >=3.0,<5.0
    - ffmpeg >=2.7,<3.0

    # Features
    - cyvlfeat >=0.4.3,<0.5

    # Visualization
    - matplotlib >=1.4,<2.0

    # Test dependencies
    - mock
    - pytest

test:
  requires:
    - coverage

  files:
    - .coveragerc

  imports:
    - menpo

  commands:
    - nosetests menpo -v --with-coverage --cover-package=menpo --with-xunit --xunit-file=/tmp/menpo.xml --xunit-testsuite-name=menpo  # [unix]
    - nosetests menpo -v --with-coverage --cover-package=menpo --with-xunit --xunit-file=C:\\menpo.xml --xunit-testsuite-name=menpo   # [win]

about:
  home: https://github.com/menpo/menpo/
  license: BSD
