package:
  name: menpo
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10,<1.11
    - cython 0.23.*

  run:
    - python
    - pathlib 1.0  # [py2k]

    # Scientific Python Stack
    - numpy >=1.10,<1.11
    - scipy 0.16.*
    - pillow  3.0.*

    # Features
    - cyvlfeat >=0.4.2,<0.5

    # Visualization
    - matplotlib >=1.4,<1.6

    # Test dependencies
    - mock 1.3.*
    - nose

test:
  requires:
    - coverage

  imports:
    - menpo

  commands:
    - nosetests menpo -v --with-coverage --cover-package=menpo

about:
  home: https://github.com/menpo/menpo/
  license: BSD

