package:
  name: menpo
  version: {{ environ['CONDACI_VERSION'] }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - numpy
    - cython

  run:
    - python
    - pathlib 1.0*  # [py2k]

    # Scientific Python Stack
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0,<2.0
    - pillow >=4.0,<6.0
    - ffmpeg >=2.7,<5.0

    # Visualization
    - matplotlib >=3,<4.0

test:
  requires:
    - pytest >=5.0,<6.0
    - pytest-cov >=2.0,<3.0
    - mock >=3.0,<4.0

  files:
    - .coveragerc

  imports:
    - menpo

  commands:
    - MPLBACKEND=Agg pytest $SP_DIR/menpo -v --cov=menpo --cov-config .coveragerc              # [linux]
    - MPLBACKEND=TKAgg pytest $SP_DIR/menpo -v --cov=menpo --cov-config .coveragerc            # [osx]
    - pytest %SP_DIR%\\menpo -v --cov=menpo --cov-config .coveragerc --junitxml=C:\\menpo.xml  # [win]


about:
  home: https://github.com/menpo/menpo/
  license: BSD
  summary: The Menpo Project Python package for handling annotated data
  description: |
    Menpo is a Menpo Project package designed from the ground up to make
    importing, manipulating and visualizing image and mesh data as simple as
    possible. In particular, we focus on annotated data which is common within
    the fields of Machine Learning and Computer Vision.
  doc_url: https://menpo.readthedocs.io/en/stable/
  dev_url: https://github.com/menpo/menpo
