package:
  name: menpo
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy 1.9.0
    - cython 0.21

  run:
    - python
    - pathlib 1.0 # [not py3k]

    # Scientific Python Stack
    - numpy 1.9.0
    - scipy 0.14.0
    - matplotlib 1.4.0
    - scikit-learn 0.15.2
    - pillow  2.5.1

    # Menpo Project
    - hdf5able 0.3.3
    - cyassimp 0.2.0
    - menpo-pyvrml97 2.3.0a4  # [not py3k]

    # Other
    - wrapt 1.9.0

    # Convienience dependences (not strictly required)
    - mock
    - nose
    - pip
    - ipython-notebook

test:
  requires:
  - coverage

  imports:
  - menpo

  commands:
  - python -c "import nose; nose.main()" -s menpo

about:
  home: https://github.com/menpo/menpo/
  license: BSD
