package:
  name: menpo
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10,<2.0
    - cython >=0.23

  run:
    - python
    - pathlib 1.0  # [py2k]

    # Scientific Python Stack
    - numpy >=1.10,<2.0
    - scipy >=0.16,<1.0
    - pillow >=3.0,<4.0
    - imageio >=1.5,<2.0

    # Features
    - cyvlfeat >=0.4.3,<0.5

    # Visualization
    - matplotlib >=1.4,<2.0

    # Test dependencies
    - mock 1.3.*
    - nose

test:
  requires:
    - coverage

  files:
    - .coveragerc

  imports:
    - menpo

  commands:
    - nosetests menpo -v --with-coverage --cover-package=menpo

about:
  home: https://github.com/menpo/menpo/
  license: BSD
