# A list of extensions that different importers support.
from pybug.io.mesh.base import AssimpImporter, WRLImporter, FIMImporter
from pybug.io.image import ImageImporter


mesh_types = {'.dae': AssimpImporter,
              '.3ds': AssimpImporter,
              '.ase': AssimpImporter,
              '.obj': AssimpImporter,
              '.ifc': AssimpImporter,
              '.xgl': AssimpImporter,
              '.zgl': AssimpImporter,
              '.ply': AssimpImporter,
              '.dxf': AssimpImporter,
              '.lwo': AssimpImporter,
              '.lws': AssimpImporter,
              '.lxo': AssimpImporter,
              '.stl': AssimpImporter,
              '.x': AssimpImporter,
              '.ac': AssimpImporter,
              '.md5': AssimpImporter,
              '.smd': AssimpImporter,
              '.vta': AssimpImporter,
              '.m3': AssimpImporter,
              '.3d': AssimpImporter,
              '.b3d': AssimpImporter,
              '.q3d': AssimpImporter,
              '.q3s': AssimpImporter,
              '.nff': AssimpImporter,
              '.off': AssimpImporter,
              '.raw': AssimpImporter,
              '.ter': AssimpImporter,
              '.mdl': AssimpImporter,
              '.hmp': AssimpImporter,
              '.ndo': AssimpImporter,
              '.ms3d': AssimpImporter,
              '.cob': AssimpImporter,
              '.scn': AssimpImporter,
              '.bvh': AssimpImporter,
              '.csm': AssimpImporter,
              '.xml': AssimpImporter,
              '.irrmesh': AssimpImporter,
              '.irr': AssimpImporter,
              '.md2': AssimpImporter,
              '.md3': AssimpImporter,
              '.pk3': AssimpImporter,
              '.mdc': AssimpImporter,
              # '.blend': AssimpImporter,
              '.wrl': WRLImporter,
              '.fim': FIMImporter}


image_types = {'.bmp': ImageImporter,
               '.dib': ImageImporter,
               '.dcx': ImageImporter,
               '.eps': ImageImporter,
               '.ps': ImageImporter,
               '.gif': ImageImporter,
               '.im': ImageImporter,
               '.jpg': ImageImporter,
               '.jpe': ImageImporter,
               '.jpeg': ImageImporter,
               '.pcd': ImageImporter,
               '.pcx': ImageImporter,
               '.png': ImageImporter,
               '.pbm': ImageImporter,
               '.pgm': ImageImporter,
               '.ppm': ImageImporter,
               '.psd': ImageImporter,
               '.tif': ImageImporter,
               '.tiff': ImageImporter,
               '.xbm': ImageImporter,
               # '.pdf': ImageImporter,
               '.xpm': ImageImporter}