# A list of extensions that different importers support.

assimp_exts = ['.dae',
               #'.blend', texture paths are problematic
               '.3ds',
               '.ase',
               '.obj',
               '.ifc',
               '.xgl',
               '.zgl',
               '.ply',
               '.dxf',
               '.lwo',
               '.lws',
               '.lxo',
               '.stl',
               '.x',
               '.ac',
               '.md5',
               '.smd',
               '.vta',
               '.m3',
               '.3d',
               '.b3d',
               '.q3d',
               '.q3s',
               '.nff',
               '.nff',
               '.off',
               '.raw',
               '.ter',
               '.mdl',
               '.hmp',
               '.ndo',
               '.ms3d',
               '.cob',
               '.scn',
               '.bvh',
               '.csm',
               '.xml',
               '.irrmesh',
               '.irr',
               '.mdl',
               '.md2',
               '.md3',
               '.pk3',
               '.mdc']

pil_exts = ['.bmp',
            '.dib',
            '.dcx',
            '.eps',
            '.ps',
            '.gif',
            '.im',
            '.jpg',
            '.jpe',
            '.jpeg',
            '.pcd',
            '.pcx',
            #'.pdf', doesn't seem to work..
            '.png',
            '.pbm',
            '.pgm',
            '.ppm',
            '.psd',
            '.tif',
            '.tiff',
            '.xbm',
            '.xpm']
