xref_map = {
'as_vector': ('function', 'menpo.base.Vectorizable.as_vector'),
'Affine': ('class', 'menpo.transform.Affine'),
'Alignment': ('class', 'menpo.transform.Alignment'),
'AlignmentAffine': ('class', 'menpo.transform.AlignmentAffine'),
'AlignmentSimilarity': ('class', 'menpo.transform.AlignmentSimilarity'),
'BooleanImage': ('class', 'menpo.image.BooleanImage'),
'Copyable': ('class', 'menpo.base.Copyable'),
'ComposableTransform': ('class', 'menpo.transform.ComposableTransform'),
'DiscreteAffine': ('class', 'menpo.transform.DiscreteAffine'),
'from_vector_inplace': ('function', 'menpo.base.Vectorizable.from_vector_inplace'),
'from_vector': ('function', 'menpo.base.Vectorizable.from_vector'),
'Homogeneous': ('class', 'menpo.transform.Homogeneous'),
'HomogFamilyAlignment': ('class', 'menpo.transform.HomogFamilyAlignment'),
'Image': ('class', 'menpo.image.Image'),
'ImageBoundaryError': ('class', 'menpo.image.ImageBoundaryError'),
'Invertible': ('class', 'menpo.transform.Invertible'),
'Landmarkable': ('class', 'menpo.landmark.Landmarkable'),
'LandmarkGroup': ('class', 'menpo.landmark.LandmarkGroup'),
'LandmarkManager': ('class', 'menpo.landmark.LandmarkManager'),
'LabellingError': ('class', 'menpo.landmark.LabellingError'),
'MaskedImage': ('class', 'menpo.image.MaskedImage'),
'MeanInstanceLinearModel': ('class', 'menpo.model.MeanInstanceLinearModel'),
'MultipleAlignment': ('class', 'menpo.transform.MultipleAlignment'),
'PCAModel': ('class', 'menpo.model.pca.PCAModel'),
'PointCloud': ('class', 'menpo.shape.PointCloud'),
'PointDirectedGraph': ('class', 'menpo.shape.PointDirectedGraph'),
'pca': ('function', 'menpo.math.pca'),
'Shape': ('class', 'menpo.shape.Shape'),
'Similarity': ('class', 'menpo.transform.Similarity'),
'Targetable': ('class', 'menpo.base.Targetable'),
'Transform': ('class', 'menpo.transform.Transform'),
'Translation': ('class', 'menpo.transform.Translation'),
'TransformChain': ('class', 'menpo.transform.TransformChain'),
'Transformable': ('class', 'menpo.transform.Transformable'),
'TriMesh': ('class', 'menpo.shape.TriMesh'),
'Vectorizable': ('class', 'menpo.base.Vectorizable'),
'view': ('function', 'menpo.visualize.Viewable.view'),
'Viewable': ('class', 'menpo.visualize.Viewable'),
'VComposable': ('class', 'menpo.transform.VComposable'),
'VInvertible': ('class', 'menpo.transform.VInvertible')
}
#
# 'GradientDescent': ('class', 'menpo.fit.gradientdescent.base.GradientDescent'),
# 'AAM': ('class', 'menpo.fitmultilevel.aam.builder.AAM'),
# 'AAMFitter': ('class', 'menpo.fitmultilevel.aam.base.AAMFitter'),
# 'AAMMultilevelFittingResult': ('class', 'menpo.fitmultilevel.fittingresult.AAMMultilevelFittingResult'),
# 'AppearanceLucasKanade': ('class', 'menpo.fit.lucaskanade.appearance.base.AppearanceLucasKanade'),
# 'Fitter': ('class', 'menpo.fit.Fitter'),
# 'FittingResult': ('class', 'menpo.fit.fittingresult.FittingResult'),
# 'GlobalPDM': ('class', 'menpo.model.modelinstance.GlobalPDM'),
# 'DL': ('class', 'menpo.base.DL'),
# 'DP': ('class', 'menpo.base.DP'),
# 'DX': ('class', 'menpo.base.DX'),
# 'MultilevelFitter': ('class', 'menpo.fitmultilevel.MultilevelFitter'),
# 'OrthoPDM':  ('class', 'menpo.model.modelinstance.OrthoPDM'),
# 'OrthoMDTransform':  ('class', 'menpo.transform.modeldriven.OrthoMDTransform'),
# 'PDM': ('class', 'menpo.model.PDM'),
# 'ModelDrivenTransform': ('class', 'menpo.transform.ModelDrivenTransform'),
# 'CLM': ('class', 'menpo.fitmultilevel.clm.builder.CLM'),
