xref_map = {
'Affine': ('class', 'menpo.transform.homogeneous.affine.Affine'),
'ComposableTransform': ('class', 'menpo.transform.base.composable.ComposableTransform'),

'DiscreteAffine': ('class', 'menpo.transform.homogeneous.affine.DiscreteAffine'),
'DL': ('class', 'menpo.base.DL'),
'DP': ('class', 'menpo.base.DP'),
'DX': ('class', 'menpo.base.DX'),
'Image': ('class', 'menpo.image.base.Image'),
'Landmarkable': ('class', 'menpo.landmark.base.Landmarkable'),
'LandmarkGroup': ('class', 'menpo.landmark.base.LandmarkGroup'),
'LandmarkManager': ('class', 'menpo.landmark.base.LandmarkManager'),
'MaskedImage': ('class', 'menpo.image.masked.MaskedImage'),
'MeanInstanceLinearModel': ('class', 'menpo.model.base.MeanInstanceLinearModel'),
'PointCloud': ('class', 'menpo.shape.pointcloud.PointCloud'),
'principal_component_decomposition': ('function', 'menpo.math.decomposition.principal_component_decomposition'),
'Shape': ('class', 'menpo.shape.base.Shape'),
'Targetable': ('class', 'menpo.base.Targetable'),
'Transform': ('class', 'menpo.transform.base.Transform'),
'TransformChain': ('class', 'menpo.transform.base.composable.TransformChain'),
'Transformable': ('class', 'menpo.transform.base.Transformable'),
'TriMesh': ('class', 'menpo.shape.mesh.TriMesh'),
'Vectorizable': ('class', 'menpo.base.Vectorizable'),
'view': ('meth', 'menpo.visualize.base.Viewable.view'),
'Viewable': ('class', 'menpo.visualize.base.Viewable')
}
