execute: mesh.cpp mesh.h driver.cpp triangle.cpp triangle.h halfedge.h halfedge.cpp vertex.cpp vertex.h vec3.h vec3.cpp
	g++ -g -Wall mesh.cpp triangle.cpp halfedge.cpp vertex.cpp vec3.cpp driver.cpp -o mesh.exe 

clean:
	rm mesh.exe 
